const SECTIONS=[
  {title:"🤖 AI / CHAT",items:[
    [".imagine <prompt>","Generate an image"," .imagine a futuristic robot"],
    [".video <prompt>","Generate a video"," .video a sunset over mountains"],
    [".newchat / .reset","Clear AI conversation memory"," .newchat"],
    [".memory","Show memory count"," .memory"],
    [".memory on/off","Enable or disable memory"," .memory on"],
    [".voice on/off","Enable or disable voice replies"," .voice on"]
  ]},
  {title:"🧭 CORE / TOOLS",items:[
    [".menu","Open all commands"," .menu"],
    [".help [language]","Detailed help with examples"," .help Hindi"],
    [".ping","Health check"," .ping"],
    [".status","Bot status"," .status"],
    [".doctor","Run diagnostics"," .doctor"],
    [".tools","Show available tools"," .tools"],
    [".provider","AI provider status"," .provider"],
    [".plan <task>","Preview execution plan"," .plan deploy my project"],
    [".agent [status]","Agent core status"," .agent status"],
    [".health","Agent health"," .health"],
    [".baileys","Baileys capability status"," .baileys"],
    [".skills","List active skills"," .skills"],
    [".mode / .ui <mode>","Set UI mode"," .mode hybrid"],
    [".language <language>","Change language"," .language Hindi"],
    [".profile","View profile"," .profile"],
    [".profile name/bio/language","Update profile"," .profile name Tohid"],
    [".settings","Open settings"," .settings"]
  ]},
  {title:"🎯 MISSIONS / AUTOMATION",items:[
    [".mission <request>","Create/start mission"," .mission check my GitHub"],
    [".mission status <id>","View mission"," .mission status 123"],
    [".mission confirm <id>","Confirm mission"," .mission confirm 123"],
    [".mission cancel <id>","Cancel mission"," .mission cancel 123"],
    [".missions","List missions"," .missions"],
    [".schedule <delay> <task>","Schedule mission"," .schedule 30m check GitHub"],
    [".schedules","List schedules"," .schedules"],
    [".schedule cancel <id>","Cancel schedule"," .schedule cancel 123"],
    [".task <request>","Start agent task"," .task inspect my repo"],
    [".tasks","Recent agent tasks"," .tasks"],
    [".workflow <task>","Multi-step workflow"," .workflow inspect and deploy project"]
  ]},
  {title:"🐙 GITHUB / DEVOPS",items:[
    ["Natural-language GitHub","Repos, files, branches, issues, PRs"," Show my GitHub repositories"],
    [".url list/add/switch/remove","Manage pairing URLs"," .url list"],
    [".pair <number>","8-digit pairing"," .pair 919876543210"],
    [".qr","QR pairing without number"," .qr"],
    [".plugin list/search/install/...","Plugin management"," .plugin list"],
    [".file list/read/backup/...","Workspace files"," .file list"],
    [".feature list/on/off","Runtime features"," .feature list"],
    [".admin","Control center"," .admin"],
    [".dashboard","Dashboard"," .dashboard"],
    [".role / .roles","RBAC roles"," .roles"],
    [".owner list/add/remove/revokeall","Delegated owners"," .owner list"],
    [".env / .config ...","Global config"," .config list"],
    [".shell <command> CONFIRM","Restricted shell"," .shell uptime CONFIRM"],
    [".maintenance on/off","Maintenance mode"," .maintenance on"]
  ]},
  {title:"📢 CHANNEL / GROUP",items:[
    [".channel <action>","WhatsApp Channel management"," .channel info <jid>"],
    [".groupstatus <text>","Send group status"," .groupstatus Hello group"],
    [".welcome on/off","Enable/disable welcome"," .welcome on"],
    [".welcome add <text> | <image URL>","Custom welcome"," .welcome add Welcome @member! | https://example.com/welcome.jpg"],
    [".welcome remove <number>","Remove custom welcome"," .welcome remove 1"],
    [".welcome list","List custom welcome"," .welcome list"],
    [".welcome clear","Clear custom welcome"," .welcome clear"],
    [".goodbye on/off","Enable/disable goodbye"," .goodbye on"],
    [".goodbye add <text> | <image URL>","Custom goodbye"," .goodbye add Goodbye @member! | https://example.com/bye.jpg"],
    [".goodbye remove <number>","Remove custom goodbye"," .goodbye remove 1"],
    [".goodbye list","List custom goodbye"," .goodbye list"],
    [".goodbye clear","Clear custom goodbye"," .goodbye clear"]
  ]},
  {title:"🛡️ GROUP PROTECTION — ADMIN ONLY",items:[
    [".antilink on/off/delete/warn/kick","Block links"," .antilink on"],
    [".antilink allow/disallow/allowed","Member exceptions"," .antilink allow 919876543210"],
    [".antistatus on/off/delete/warn/kick","Block status mentions"," .antistatus on"],
    [".antistatus allow/disallow/allowed","Member exceptions"," .antistatus allow @member"],
    [".antitag on/off/delete/warn/kick","Block member tags"," .antitag on"],
    [".antitag allow/disallow/allowed","Member exceptions"," .antitag allow @member"],
    [".antitagall on/off/delete/warn/kick","Block mass tags"," .antitagall on"],
    [".antitagall allow/disallow/allowed","Member exceptions"," .antitagall allow @member"],
    [".antibot on/off/delete/warn/kick","Configured bot protection"," .antibot on"],
    [".antibot add/remove/list/clear","Manage bot numbers"," .antibot add 919876543210"],
    [".antibot allow/disallow/allowed","Member exceptions"," .antibot allow @member"],
    [".antipdm on/off","Protect admin changes"," .antipdm on"],
    [".antipdm allow/disallow/allowed","Actor exceptions"," .antipdm allow @member"],
    [".antigroupstatus on/off/delete/warn/kick","Dedicated group-status protection"," .antigroupstatus on"],
    [".security status|strict|normal|relaxed|off","Group security presets"," .security strict"],
    [".warn <number/@mention/reply>","Issue a moderation warning"," .warn @member"],
    [".warnings <number/@mention/reply>","Show member warnings"," .warnings @member"],
    [".resetwarn <number/@mention/reply>","Reset member warnings"," .resetwarn @member"],
    [".warnlimit <1-20>","Set automatic warning limit"," .warnlimit 3"],
    [".modlog","Show recent moderation events"," .modlog"],
    [".antibad on/off/delete/warn/kick","Detect bad words"," .antibad on"],
    [".antibad add/remove/list/clear","Custom bad words"," .antibad add example"],
    [".antibad allow/disallow/allowed","Member exceptions"," .antibad allow @member"]
  ]},
  {title:"🛡️ GROUP CONTROL CENTER",items:[
    [".group status|backup|backups|restore <id>","Central group policy control"," .group status"],
    [".security status|strict|normal|relaxed|off","Security presets"," .security strict"],
    [".lock links|media|images|video|audio|voice|documents|stickers|forwards|polls|contacts|locations|newmembers|mentions|all [minutes]","Temporary group locks"," .lock links 30"],
    [".unlock <lock>","Unlock group rule"," .unlock links"],
    [".groupstats","Group analytics"," .groupstats"],
    [".member <number/@mention/reply>","Member reputation profile"," .member @member"],
    [".warn <number/@mention/reply>","Issue warning"," .warn @member"],
    [".warnings <number/@mention/reply>","Show warnings"," .warnings @member"],
    [".resetwarn <number/@mention/reply>","Reset warnings"," .resetwarn @member"],
    [".warnlimit <1-20>","Set warning limit"," .warnlimit 3"],
    [".modlog","Show moderation log"," .modlog"]
  ]},
  {title:"🛡️ GROUP AI / SECURITY OS",items:[
    [".antispam on/off/delete/warn/mute/kick","Flood and repeat-message protection"," .antispam on"],
    [".antispam <count> <window>","Configure spam threshold"," .antispam 6 8s"],
    [".mute [duration]","Mute entire group; admins remain allowed"," .mute 10m"],
    [".unmute","Unmute entire group"," .unmute"],
    [".msgmute @member <duration> [reason]","Mute one member's messages"," .msgmute @member 10m spam"],
    [".msgunmute @member","Remove one-member message mute"," .msgunmute @member"],
    [".msgmuted","List members with message mute"," .msgmuted"],
    [".raid on/off/status","Raid protection"," .raid on"],
    [".raid lockdown [minutes]","Emergency lockdown"," .raid lockdown 10"],
    [".raid unlock","Disable lockdown"," .raid unlock"],
    [".verification on/off/status","New-member verification"," .verification on"],
    [".verify","Verify yourself"," .verify"],
    [".schedule lock/unlock <lock> <HH:MM>","Schedule group lock"," .schedule lock links 23:00"],
    [".activity","Group activity analytics"," .activity"],
    [".topchatters","Top chatters"," .topchatters"],
    [".modstats","Moderation analytics"," .modstats"]
  ]},
  {title:"👤 USER / ADMIN",items:[
    [".block <number>","Block user"," .block 919876543210"],
    [".unblock <number>","Unblock user"," .unblock 919876543210"],
    [".stats","Owner statistics"," .stats"]
  ]}

  {title:"📥 MEDIA / DOWNLOADER / SEARCH / FUN",items:[
    [".play <query>","Play/download audio — API can be added later",".play kesariya"],
    [".song <query>","Download song — API can be added later",".song arijit singh"],
    [".ytmp3 <url>","YouTube MP3 — API can be added later",".ytmp3 <url>"],
    [".ytmp4 <url>","YouTube MP4 — API can be added later",".ytmp4 <url>"],
    [".facebook <url>","Facebook downloader — API can be added later",".facebook <url>"],
    [".instagram <url>","Instagram downloader — API can be added later",".instagram <url>"],
    [".tiktok <url>","TikTok downloader — API can be added later",".tiktok <url>"],
    [".twitter <url>","X/Twitter downloader — API can be added later",".twitter <url>"],
    [".pinterest <url>","Pinterest downloader — API can be added later",".pinterest <url>"],
    [".spotify <url/query>","Spotify resolver — API can be added later",".spotify <url>"],
    [".mediafire <url>","MediaFire downloader — API can be added later",".mediafire <url>"],
    [".apk <query>","APK search/download — API can be added later",".apk whatsapp"],
    [".search <query>","Web search — API can be added later",".search latest node.js"],
    [".weather <city>","Weather — API can be added later",".weather Delhi"],
    [".translate <text>","Translate text",".translate hello hindi"],
    [".sticker","Create sticker from replied media",".sticker"],
    [".toimg","Convert sticker/media to image",".toimg"],
    [".tomp3","Convert replied media to audio",".tomp3"],
    [".tovideo","Convert replied media to video",".tovideo"],
    [".quiz","Start quiz",".quiz"],
    [".trivia","Trivia question",".trivia"],
    [".truth","Truth prompt",".truth"],
    [".dare","Dare prompt",".dare"],
    [".joke","Tell a joke",".joke"],
    [".quote","Random quote",".quote"],
    [".fact","Random fact",".fact"],
    [".8ball <question>","Magic 8-ball",".8ball will I win?"]
  ]},
  {title:"✍️ TEXT / AI / VOICE",items:[
    [".ask <question>","Ask AI agent",".ask explain Node.js"],
    [".summarize <text>","Summarize content",".summarize <text>"],
    [".rewrite <text>","Rewrite content",".rewrite <text>"],
    [".vision","Analyze replied image",".vision"],
    [".tts <text>","Text to speech — provider can be added later",".tts hello Tohid"],
    [".stt","Transcribe replied audio",".stt"],
    [".font <text>","Stylize text",".font Tohid"],
    [".bold <text>","Bold text",".bold Tohid"],
    [".italic <text>","Italic text",".italic Tohid"],
    [".reverse <text>","Reverse text",".reverse Tohid"],
    [".base64 <text>","Base64 encode/decode",".base64 Tohid"]
  ]},
  {title:"👥 GROUP / MODERATION EXTENSIONS",items:[
    [".kick @member","Remove member",".kick @member"],
    [".add <number>","Add member",".add 919876543210"],
    [".promote @member","Promote member",".promote @member"],
    [".demote @member","Demote member",".demote @member"],
    [".tagall","Mention all members",".tagall"],
    [".hidetag <text>","Hidden group mention",".hidetag announcement"],
    [".groupinfo","Group information",".groupinfo"],
    [".admins","List group admins",".admins"],
    [".link","Get group invite link",".link"],
    [".revoke","Revoke group invite link",".revoke"],
    [".setname <name>","Change group name",".setname TOHID TEST"],
    [".setdesc <text>","Change group description",".setdesc TOHID AGENT"]
  ]},
  {title:"👑 OWNER / BOT MANAGEMENT EXTENSIONS",items:[
    [".restart","Restart bot",".restart"],
    [".update","Update bot/plugin code",".update"],
    [".broadcast <text>","Broadcast message",".broadcast hello"],
    [".listusers","List bot users",".listusers"],
    [".listgroups","List bot groups",".listgroups"],
    [".blockuser <number>","Block bot user",".blockuser 919876543210"],
    [".unblockuser <number>","Unblock bot user",".unblockuser 919876543210"]
  ]},
];return s.items.map(([cmd,desc])=>({title:cmd.slice(0,24),description:desc.slice(0,68),id:idFor(cmd)}));}
function categoryMap(){const out={};SECTIONS.forEach((s,i)=>out["tohid_cat_"+i]=i);return out;}
function commandMap(){const out={};for(const s of SECTIONS)for(const [cmd,,example] of s.items)out[idFor(cmd)]=example.trim();return out;}
module.exports={SECTIONS,text,menuText,categoryRows,commandRows,categoryMap,commandMap,idFor};
];
function text(){
  return SECTIONS.map(s=>s.title+"\\n"+s.items.map(([cmd,desc,example])=>"• "+cmd+" — "+desc+"\\n  Example: "+example.trim()).join("\\n")).join("\\n\\n");
}
function menuText(){return "🤖 *TOHID-AGENT — ALL COMMANDS*\\n\\n"+text();}
function idFor(cmd){return "tohid_cmd_"+cmd.replace(/[^a-z0-9]+/gi,"_").slice(0,70);}
function categoryRows(){return SECTIONS.map((s,i)=>({title:s.title,description:"Open this command category",id:"tohid_cat_"+i}));}
function commandRows(index){const s=SECTIONS[index];if(!s)return [];
