const {MongoClient}=require("mongodb");
const cfg=require("../config");
let client,db;
async function connect(){if(!cfg.mongoUri)return null;if(db)return db;client=new MongoClient(cfg.mongoUri);await client.connect();db=client.db(cfg.mongoDb);await Promise.all([
db.collection("users").createIndex({jid:1},{unique:true}),db.collection("conversations").createIndex({jid:1},{unique:true}),db.collection("usage").createIndex({jid:1},{unique:true}),db.collection("blocked").createIndex({jid:1},{unique:true}),db.collection("settings").createIndex({jid:1},{unique:true}),db.collection("profiles").createIndex({jid:1},{unique:true}),db.collection("pending_writes").createIndex({jid:1},{unique:true}),db.collection("audit_logs").createIndex({jid:1,createdAt:-1}),db.collection("agent_tasks").createIndex({jid:1,createdAt:-1}),db.collection("missions").createIndex({jid:1,createdAt:-1}),db.collection("missions").createIndex({jid:1,status:1,updatedAt:-1}),db.collection("scheduled_jobs").createIndex({status:1,runAt:1}),db.collection("scheduled_jobs").createIndex({jid:1,runAt:1}),db.collection("delegated_owners").createIndex({number:1},{unique:true})]);return db;}
async function close(){if(client){await client.close();client=null;db=null;}}
async function getMemory(jid){const d=await connect();if(!d)return[];return(await d.collection("conversations").findOne({jid}))?.messages||[];}
async function saveMemory(jid,messages){const d=await connect();if(d)await d.collection("conversations").updateOne({jid},{$set:{messages:messages.slice(-cfg.maxMemoryMessages),updatedAt:new Date()}},{upsert:true});}
async function clearMemory(jid){const d=await connect();if(d)await d.collection("conversations").deleteOne({jid});}
async function getProfile(jid){const d=await connect();if(!d)return{};return(await d.collection("profiles").findOne({jid}))||{};}
async function setProfile(jid,patch){const d=await connect();if(!d)return{};await d.collection("profiles").updateOne({jid},{$set:{...patch,updatedAt:new Date()}},{upsert:true});return getProfile(jid);}
async function track(jid,type){const d=await connect();if(!d)return;await d.collection("users").updateOne({jid},{$set:{lastSeen:new Date()},$setOnInsert:{createdAt:new Date()}},{upsert:true});await d.collection("usage").updateOne({jid},{$inc:{[type]:1},$set:{updatedAt:new Date()}},{upsert:true});}
async function setBlocked(jid,blocked=true){const d=await connect();if(!d)return false;if(blocked)await d.collection("blocked").updateOne({jid},{$set:{jid,updatedAt:new Date()}},{upsert:true});else await d.collection("blocked").deleteOne({jid});return true;}
async function isBlocked(jid){const d=await connect();if(!d)return false;return!!(await d.collection("blocked").findOne({jid}));}
async function getSettings(jid){const d=await connect();if(!d)return{};return(await d.collection("settings").findOne({jid}))||{};}
async function setSettings(jid,patch){const d=await connect();if(!d)return{};await d.collection("settings").updateOne({jid},{$set:{...patch,updatedAt:new Date()}},{upsert:true});return getSettings(jid);}
async function savePending(jid,pending){const d=await connect();if(!d)return;if(pending)await d.collection("pending_writes").updateOne({jid},{$set:{jid,pending,updatedAt:new Date()}},{upsert:true});else await d.collection("pending_writes").deleteOne({jid});}
async function getPending(jid){const d=await connect();if(!d)return null;return(await d.collection("pending_writes").findOne({jid}))?.pending||null;}
async function audit(jid,action,meta={}){const d=await connect();if(d)await d.collection("audit_logs").insertOne({jid,action,meta,createdAt:new Date()});}
async function getGlobalConfig(){const d=await connect();if(!d)return{};return(await d.collection("global_config").findOne({_id:"runtime"}))?.values||{};}
async function setGlobalConfig(patch){const d=await connect();if(!d)return{};await d.collection("global_config").updateOne({_id:"runtime"},{$set:{values:patch,updatedAt:new Date()}},{upsert:true});return getGlobalConfig();}\nasync function getDelegatedOwners(){const d=await connect();if(!d)return[];return(await d.collection("delegated_owners").find({}).sort({createdAt:1}).toArray()).map(x=>x.number);}\nasync function addDelegatedOwner(number,addedBy){const d=await connect();if(!d)return false;const n=String(number||"").replace(/\\D/g,"");if(!n)return false;await d.collection("delegated_owners").updateOne({number:n},{$set:{number:n,updatedAt:new Date()},$setOnInsert:{createdAt:new Date(),addedBy}},{upsert:true});return true;}
async function removeDelegatedOwner(number){const d=await connect();if(!d)return false;const n=String(number||"").replace(/\\D/g,"");if(!n)return false;await d.collection("delegated_owners").deleteOne({number:n});return true;}
async function clearDelegatedOwners(){const d=await connect();if(!d)return 0;return (await d.collection("delegated_owners").deleteMany({})).deletedCount||0;}
async function stats(){const d=await connect();if(!d)return{database:false};const[users,usage,blocked]=await Promise.all([d.collection("users").countDocuments(),d.collection("usage").aggregate([{$group:{_id:null,chat:{$sum:"$chat"},voice:{$sum:"$voice"},image:{$sum:"$image"},video:{$sum:"$video"},github_write:{$sum:"$github_write"},tool:{$sum:"$tool"}}}]).toArray(),d.collection("blocked").countDocuments()]);return{database:true,users,blocked,usage:usage[0]||{chat:0,voice:0,image:0,video:0,github_write:0,tool:0}};}
module.exports={connect,close,getMemory,saveMemory,clearMemory,getProfile,setProfile,track,setBlocked,isBlocked,getSettings,setSettings,savePending,getPending,audit,getGlobalConfig,setGlobalConfig,getDelegatedOwners,addDelegatedOwner,removeDelegatedOwner,clearDelegatedOwners,stats};