const crypto=require("crypto");
const policy=require("./groupPolicyEngine");
const spamState=new Map(),raidState=new Map();
const now=()=>Date.now();
const normalize=j=>String(j||"").split(":")[0].replace(/\?.*$/,"");
function isAdmin(meta,j){const n=normalize(j),p=(meta?.participants||[]).find(x=>normalize(x.id)===n||normalize(x.jid)===n||normalize(x.lid)===n||normalize(x.pn)===n);return !!p&&(p.admin==="admin"||p.admin==="superadmin");}
const botAdmin=(meta,sock)=>isAdmin(meta,normalize(sock?.user?.id));
function unwrap(m){if(!m||typeof m!=="object")return m||{};for(const k of ["ephemeralMessage","viewOnceMessage","viewOnceMessageV2","documentWithCaptionMessage","editedMessage"])if(m[k]?.message)return unwrap(m[k].message);return m;}
function ctx(m){const x=unwrap(m);return x.extendedTextMessage?.contextInfo||x.imageMessage?.contextInfo||x.videoMessage?.contextInfo||x.documentMessage?.contextInfo||x.audioMessage?.contextInfo||x.stickerMessage?.contextInfo||x.interactiveMessage?.contextInfo||x.listMessage?.contextInfo||x.templateMessage?.contextInfo||x.contextInfo||{};}
function durationMs(v){const m=String(v||"").match(/^(\d+)(s|m|h|d)$/i);if(!m)return 0;const n=+m[1],u=m[2].toLowerCase();return n*(u==="s"?1e3:u==="m"?6e4:u==="h"?36e5:864e5);}
async function get(db,jid){const s=await db.getSettings(jid),sec=policy.state(s).security;return {...s,security:{...sec,spam:sec.spam||{enabled:false,action:"warn",threshold:6,windowMs:8000,repeat:3},mutes:Array.isArray(sec.mutes)?sec.mutes:[],raid:sec.raid||{enabled:false,windowMs:30000,threshold:4,lockMinutes:10},verification:sec.verification||{enabled:false,timeoutMs:120000,pending:[]},analytics:sec.analytics||{messages:0,deleted:0,warnings:0,kicks:0,joins:0,leaves:0,chatters:{}},groupSchedules:Array.isArray(sec.groupSchedules)?sec.groupSchedules:[]}};}
const save=(db,jid,s)=>db.setSettings(jid,s);
function log(s,e){s.security=policy.state(s).security;s.security.modlog=[...(s.security.modlog||[]),{...e,time:new Date().toISOString()}].slice(-100);return s;}
function target(meta,msg,parts){const c=ctx(msg?.message||msg),m=c.mentionedJid?.[0]||c.participant;if(m)return normalize(m);const n=(parts||[]).slice(2).find(x=>/\d{7,15}/.test(x));return n?String(n).replace(/\D/g,""):null;}
function hash(text,msg){return crypto.createHash("sha256").update(String(text||"").trim().toLowerCase().replace(/\s+/g," ")+"|"+Object.keys(unwrap(msg?.message||{})).sort().join(",")).digest("hex");}
async function handleCommand({sock,msg,jid,sender,text,db,send}){
 if(!jid.endsWith("@g.us"))return false;
 const p=String(text||"").trim().split(/\s+/),name=(p[0]||"").slice(1).toLowerCase(),sub=(p[1]||"").toLowerCase();
 if(name==="verify"){const s=await get(db,jid),me=normalize(sender),q=s.security.verification.pending||[],hit=q.find(x=>normalize(x.jid)===me);if(!hit){await send(sock,jid,"ℹ️ No pending verification.",{category:"security"});return true;}s.security.verification.pending=q.filter(x=>normalize(x.jid)!==me);await save(db,jid,s);await send(sock,jid,"✅ @"+me.split("@")[0]+" verified.",{mentions:[sender],category:"security"});return true;}
 const names=["antispam","mute","unmute","msgmute","msgunmute","msgmuted","raid","verification","schedule","activity","topchatters","modstats"];if(!names.includes(name))return false;
 let meta;try{meta=await sock.groupMetadata(jid);}catch{return true;}
 if(!isAdmin(meta,sender)){if(name==="verification"&&sub==="status"){const s=await get(db,jid);await send(sock,jid,"🔐 Verification: "+(s.security.verification.enabled?"ON":"OFF"),{category:"security"});return true;}await send(sock,jid,"⛔ Group admin only.",{category:"security"});return true;}
 let s=await get(db,jid);
 if(name==="antispam"){if(["on","off","delete","warn","mute","kick"].includes(sub)){s.security.spam.enabled=sub!=="off";if(sub!=="on"&&sub!=="off")s.security.spam.action=sub;await save(db,jid,s);await send(sock,jid,"🛡️ AntiSpam: *"+(s.security.spam.enabled?s.security.spam.action.toUpperCase():"OFF")+"*",{category:"security"});return true;}const n=+p[1],w=durationMs(p[2]);if(Number.isInteger(n)&&n>=3&&n<=50){s.security.spam.threshold=n;if(w)s.security.spam.windowMs=w;await save(db,jid,s);await send(sock,jid,"✅ AntiSpam threshold: "+n,{category:"security"});return true;}await send(sock,jid,"Usage: .antispam on/off/delete/warn/mute/kick | .antispam 6 8s",{category:"security"});return true;}
 if(name==="mute"){const minutes=durationMs(p[1])/60000;s=policy.setLock(s,"all",true,minutes||null);s=log(s,{type:"group_mute",actor:sender,duration:p[1]||"permanent"});await save(db,jid,s);await send(sock,jid,"🔇 *GROUP MUTED*"+(p[1]?" for "+p[1]:" permanently")+"\nMembers cannot send messages; admins remain allowed.",{category:"security"});return true;}
 if(name==="unmute"){s=policy.setLock(s,"all",false,0);s=log(s,{type:"group_unmute",actor:sender});await save(db,jid,s);await send(sock,jid,"🔊 *GROUP UNMUTED* — normal messaging restored.",{category:"security"});return true;}
 if(name==="msgmute"){const t=target(meta,msg,p),ms=durationMs(p[2]);if(!t||!ms){await send(sock,jid,"Usage: .msgmute @member 10m [reason]",{category:"security"});return true;}if(isAdmin(meta,t)){await send(sock,jid,"❌ Admin cannot be msgmuted.",{category:"security"});return true;}s.security.mutes=[...s.security.mutes.filter(x=>normalize(x.jid)!==t),{jid:t,expiresAt:now()+ms,reason:p.slice(3).join(" ")||"manual msgmute"}];s=log(s,{type:"msgmute",actor:sender,target:t,reason:p.slice(3).join(" ")||null});await save(db,jid,s);await send(sock,jid,"🔇 @"+t.split("@")[0]+" msgmuted for "+p[2]+".",{mentions:[t],category:"security"});return true;}
 if(name==="msgunmute"){const t=target(meta,msg,p);if(!t){await send(sock,jid,"Usage: .msgunmute @member",{category:"security"});return true;}s.security.mutes=s.security.mutes.filter(x=>normalize(x.jid)!==t);s=log(s,{type:"msgunmute",actor:sender,target:t});await save(db,jid,s);await send(sock,jid,"🔊 @"+t.split("@")[0]+" msgunmuted.",{mentions:[t],category:"security"});return true;}
 if(name==="msgmuted"){const a=s.security.mutes.filter(x=>!x.expiresAt||x.expiresAt>now());await send(sock,jid,"🔇 *MSG MUTED MEMBERS*\n\n"+(a.map(x=>"• "+x.jid+" — "+(x.expiresAt?new Date(x.expiresAt).toLocaleString():"permanent")+" — "+(x.reason||"manual")).join("\n")||"• None"),{category:"security"});return true;}
 if(name==="raid"){if(sub==="status"){await send(sock,jid,"🚨 Raid: *"+(s.security.raid.enabled?"ON":"OFF")+"*\nThreshold: "+s.security.raid.threshold+" joins / "+Math.round(s.security.raid.windowMs/1000)+"s",{category:"security"});return true;}if(sub==="on"||sub==="off"){s.security.raid.enabled=sub==="on";await save(db,jid,s);await send(sock,jid,"🚨 Raid protection: *"+(s.security.raid.enabled?"ON":"OFF")+"*",{category:"security"});return true;}if(sub==="lockdown"){let n=policy.setLock(s,"newmembers",true,+p[2]||10);n=policy.setLock(n,"links",true,+p[2]||10);n=policy.setLock(n,"media",true,+p[2]||10);await save(db,jid,n);await send(sock,jid,"🚨 *RAID LOCKDOWN ENABLED*",{category:"security"});return true;}if(sub==="unlock"){s=policy.setLock(s,"newmembers",false,0);s=policy.setLock(s,"links",false,0);s=policy.setLock(s,"media",false,0);await save(db,jid,s);await send(sock,jid,"🔓 Raid lockdown disabled.",{category:"security"});return true;}await send(sock,jid,"Usage: .raid on/off/status/lockdown [minutes]",{category:"security"});return true;}
 if(name==="verification"){if(sub==="on"||sub==="off"){s.security.verification.enabled=sub==="on";await save(db,jid,s);await send(sock,jid,"🔐 Verification: *"+(s.security.verification.enabled?"ON":"OFF")+"*",{category:"security"});return true;}if(sub==="status"){await send(sock,jid,"🔐 Verification: *"+(s.security.verification.enabled?"ON":"OFF")+"*\nPending: "+s.security.verification.pending.length,{category:"security"});return true;}await send(sock,jid,"Usage: .verification on/off/status",{category:"security"});return true;}
 if(name==="schedule"){if(!["lock","unlock"].includes(sub)){await send(sock,jid,"Usage: .schedule lock links 23:00 [minutes]",{category:"security"});return true;}const lock=String(p[2]||"").toLowerCase(),time=String(p[3]||"");if(!policy.LOCKS.includes(lock)||!/^[0-2]\d:[0-5]\d$/.test(time)){await send(sock,jid,"Usage: .schedule lock links 23:00 [minutes]",{category:"security"});return true;}const item={id:Date.now().toString(36),action:sub,lock,time,minutes:+p[4]||0,enabled:true};s.security.groupSchedules=[...s.security.groupSchedules,item].slice(-50);await save(db,jid,s);await send(sock,jid,"⏰ Scheduled "+sub+" "+lock+" at "+time+" (ID "+item.id+")",{category:"security"});return true;}
 if(name==="activity"){const a=s.security.analytics;await send(sock,jid,"📈 *GROUP ACTIVITY*\n\nMessages: "+a.messages+"\nDeleted: "+a.deleted+"\nWarnings: "+a.warnings+"\nKicks: "+a.kicks+"\nJoins: "+a.joins+"\nLeaves: "+a.leaves,{category:"security"});return true;}
 if(name==="topchatters"){const a=s.security.analytics.chatters||{},top=Object.entries(a).sort((x,y)=>y[1]-x[1]).slice(0,10);await send(sock,jid,"🏆 *TOP CHATTERS*\n\n"+(top.map(([u,n],i)=>(i+1)+". "+u+" — "+n).join("\n")||"• No data yet."),{category:"security"});return true;}
 if(name==="modstats"){const c={};for(const x of s.security.modlog||[])c[x.type]=(c[x.type]||0)+1;await send(sock,jid,"📊 *MODERATION STATS*\n\n"+(Object.entries(c).map(([k,v])=>"• "+k+": "+v).join("\n")||"• No events."),{category:"security"});return true;}
 return false;
}
async function inspect({sock,msg,jid,sender,text,db,send}){
 if(!jid.endsWith("@g.us"))return false;let meta;try{meta=await sock.groupMetadata(jid);}catch{return false;}
 const s=await get(db,jid),me=normalize(sender),mute=s.security.mutes.find(x=>normalize(x.jid)===me);
 if(mute&&!isAdmin(meta,sender)){if(mute.expiresAt&&mute.expiresAt<=now()){s.security.mutes=s.security.mutes.filter(x=>normalize(x.jid)!==me);await save(db,jid,s);}else{if(botAdmin(meta,sock))try{await sock.sendMessage(jid,{delete:msg.key});}catch{}return true;}}
 if(s.security.spam.enabled&&!isAdmin(meta,sender)){const k=jid+"|"+me,t=now(),h=hash(text,msg);let a=spamState.get(k)||[];a=a.filter(x=>t-x.t<=Number(s.security.spam.windowMs||8000));a.push({t,h});spamState.set(k,a);const repeats=a.filter(x=>x.h===h).length;if(a.length>=Number(s.security.spam.threshold||6)||repeats>=Number(s.security.spam.repeat||3)){const act=s.security.spam.action||"warn";if(botAdmin(meta,sock)&&["delete","mute","warn"].includes(act))try{await sock.sendMessage(jid,{delete:msg.key});s.security.analytics.deleted++;}catch{}if(act==="mute")s.security.mutes=[...s.security.mutes,{jid:sender,expiresAt:now()+300000,reason:"spam"}];if(act==="kick"&&botAdmin(meta,sock))try{await sock.groupParticipantsUpdate(jid,[sender],"remove");s.security.analytics.kicks++;}catch{}if(act==="warn"){s.warnings={...(s.warnings||{}),[sender]:(+s.warnings?.[sender]||0)+1};s.security.analytics.warnings++;}s=log(s,{type:"anti_spam",target:sender,action:act});await save(db,jid,s);await send(sock,jid,"⚠️ @"+me.split("@")[0]+" spam detected ("+act+").",{mentions:[sender],category:"security"});spamState.set(k,[]);return true;}}
 const a=s.security.analytics;a.messages=Number(a.messages||0)+1;a.chatters={...(a.chatters||{}),[me]:(Number(a.chatters?.[me])||0)+1};a.lastActivity=new Date().toISOString();if(a.messages%10===0)await save(db,jid,s);
 return false;
}
async function handleParticipantUpdate({sock,id,participants,action,db,send}){
 if(!id?.endsWith("@g.us"))return false;let s=await get(db,id),meta;try{meta=await sock.groupMetadata(id);}catch{return false;}const list=(participants||[]).filter(Boolean);
 if(action==="add"){s.security.analytics.joins=Number(s.security.analytics.joins||0)+list.length;
  if(s.security.raid.enabled){const t=now(),a=(raidState.get(id)||[]).filter(x=>t-x<s.security.raid.windowMs);a.push(...list.map(()=>t));raidState.set(id,a);if(a.length>=s.security.raid.threshold&&botAdmin(meta,sock)){let n=policy.setLock(s,"newmembers",true,s.security.raid.lockMinutes||10);n=policy.setLock(n,"links",true,s.security.raid.lockMinutes||10);n=policy.setLock(n,"media",true,s.security.raid.lockMinutes||10);s=n;await send(sock,id,"🚨 *RAID DETECTED* — temporary lockdown enabled.",{category:"security"});raidState.set(id,[]);}}
  if(s.security.verification.enabled){s.security.verification.pending=[...(s.security.verification.pending||[]),...list.map(p=>({jid:p,expiresAt:now()+Number(s.security.verification.timeoutMs||120000)}))];if(botAdmin(meta,sock))for(const p of list)await send(sock,id,"🔐 Welcome @"+String(p).split("@")[0]+"! Send .verify within 2 minutes.",{mentions:[p],category:"security"});}
 }else if(action==="remove")s.security.analytics.leaves=Number(s.security.analytics.leaves||0)+list.length;
 await save(db,id,s);return false;
}
module.exports={handleCommand,inspect,handleParticipantUpdate};