const axios=require("axios");
const cfg=require("../config");
function api(){if(!cfg.herokuToken)throw new Error("HEROKU_API_KEY is not configured.");return axios.create({baseURL:"https://api.heroku.com",headers:{Authorization:"Bearer "+cfg.herokuToken,Accept:"application/vnd.heroku+json; version=3","Content-Type":"application/json","User-Agent":"TOHID-AGENT-by-Tohid"},timeout:cfg.requestTimeoutMs});}
async function listApps(){const r=await api().get("/apps",{params:{max:100}});return r.data.map(x=>({name:x.name,id:x.id,region:x.region?.name,stack:x.stack?.name,web_url:x.web_url,maintenance:x.maintenance,updated_at:x.updated_at}));}
async function info(app){const r=await api().get("/apps/"+encodeURIComponent(app));return {name:r.data.name,id:r.data.id,web_url:r.data.web_url,region:r.data.region?.name,stack:r.data.stack?.name,maintenance:r.data.maintenance,released_at:r.data.released_at,updated_at:r.data.updated_at};}
async function formation(app){const r=await api().get("/apps/"+encodeURIComponent(app)+"/formation");return r.data.map(x=>({type:x.type,quantity:x.quantity,size:x.dyno_size?.name||x.size,command:x.command}));}
async function restart(app,type){const url="/apps/"+encodeURIComponent(app)+(type?"/formations/"+encodeURIComponent(type):"/dynos");const r=await api().delete(url);return {app,type:type||"all",status:r.status===202?"restart_requested":"accepted"};}
async function stop(app){const current=await formation(app);if(!current.length)return{app,status:"no_process_types"};const updates=current.map(x=>({type:x.type,quantity:0}));const r=await api().patch("/apps/"+encodeURIComponent(app)+"/formation",{updates});return {app,status:"stopped",formation:r.data.map(x=>({type:x.type,quantity:x.quantity}))};}
async function start(app,processes){const current=await formation(app);if(!current.length)throw new Error("No process types found for this Heroku app.");const requested=String(processes||"").trim();const updates=current.map(x=>{const m=requested.match(new RegExp("(?:^|\\s)"+x.type+"=(\\d+)"));return {type:x.type,quantity:m?Number(m[1]):1};});const r=await api().patch("/apps/"+encodeURIComponent(app)+"/formation",{updates});return {app,status:"started",formation:r.data.map(x=>({type:x.type,quantity:x.quantity}))};}
async function scale(app,updates){if(!Array.isArray(updates)||!updates.length)throw new Error("Provide process updates such as web=1 worker=0.");const parsed=updates.map(x=>{const m=String(x).match(/^([\w-]+)=(\d+)$/);if(!m)throw new Error("Invalid scale entry: "+x);return{type:m[1],quantity:Number(m[2])};});const r=await api().patch("/apps/"+encodeURIComponent(app)+"/formation",{updates:parsed});return r.data.map(x=>({type:x.type,quantity:x.quantity,size:x.dyno_size?.name||x.size}));}
async function releases(app,limit=10){const r=await api().get("/apps/"+encodeURIComponent(app)+"/releases",{headers:{"Range":"version ..; max="+Math.min(Math.max(Number(limit)||10,1),50)}});return r.data.map(x=>({id:x.id,version:x.version,status:x.status,current:x.current,description:x.description,created_at:x.created_at,updated_at:x.updated_at,eligible_for_rollback:x.eligible_for_rollback}));}
async function releaseInfo(app,release){const r=await api().get("/apps/"+encodeURIComponent(app)+"/releases/"+encodeURIComponent(release));const x=r.data;return {id:x.id,version:x.version,status:x.status,current:x.current,description:x.description,created_at:x.created_at,updated_at:x.updated_at,eligible_for_rollback:x.eligible_for_rollback,output_stream_url:x.output_stream_url};}
async function rollback(app,release){const r=await api().post("/apps/"+encodeURIComponent(app)+"/releases",{release});return {app,release:r.data.version,status:r.data.status,id:r.data.id};}
async function builds(app,limit=10){const r=await api().get("/apps/"+encodeURIComponent(app)+"/builds",{headers:{"Range":"id ..; max="+Math.min(Math.max(Number(limit)||10,1),50)}});return r.data.map(x=>({id:x.id,status:x.status,created_at:x.created_at,updated_at:x.updated_at,source_version:x.source_blob?.version,release_id:x.release?.id,output_stream_url:x.output_stream_url}));}
async function buildInfo(app,build){const r=await api().get("/apps/"+encodeURIComponent(app)+"/builds/"+encodeURIComponent(build));const x=r.data;return {id:x.id,status:x.status,created_at:x.created_at,updated_at:x.updated_at,source_blob:x.source_blob,release:x.release,output_stream_url:x.output_stream_url};}
async function buildResult(app,build){const r=await api().get("/apps/"+encodeURIComponent(app)+"/builds/"+encodeURIComponent(build)+"/result");return r.data;}
async function cancelBuild(app,build){const r=await api().delete("/apps/"+encodeURIComponent(app)+"/builds/"+encodeURIComponent(build));return {app,build,status:r.status===200?"cancelled":"accepted"};}
async function logs(app,options={}){const params={lines:Math.min(Math.max(Number(options.lines)||100,1),500)};if(options.source)params.source=options.source;if(options.dyno)params.dyno=options.dyno;const r=await api().post("/apps/"+encodeURIComponent(app)+"/log-sessions",params);const logUrl=r.data?.logplex_url;if(!logUrl)return{app,lines:[]};const log=await axios.get(logUrl,{timeout:cfg.requestTimeoutMs,responseType:"text"});return {app,source:options.source||null,dyno:options.dyno||null,lines:String(log.data||"").split("\n").filter(Boolean).slice(-params.lines)};}
async function configVars(app){const r=await api().get("/apps/"+encodeURIComponent(app)+"/config-vars");return Object.keys(r.data).sort().map(key=>({key,value:r.data[key]===null?null:"[configured]"}));}
async function setConfigVar(app,key,value){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(String(key)))throw new Error("Invalid config var name.");const r=await api().patch("/apps/"+encodeURIComponent(app)+"/config-vars",{[key]:String(value)});return {app,updated:key,configured:r.data[key]!==undefined};}
async function deleteConfigVar(app,key){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(String(key)))throw new Error("Invalid config var name.");const r=await api().patch("/apps/"+encodeURIComponent(app)+"/config-vars",{[key]:null});return {app,deleted:key,configured:r.data[key]!==undefined};}
async function maintenance(app,enabled){const r=await api().patch("/apps/"+encodeURIComponent(app),{maintenance:Boolean(enabled)});return {app,maintenance:r.data.maintenance};}
async function redeploy(app,sourceUrl,version="v7.3"){if(!sourceUrl)throw new Error("A public source tarball URL is required for Platform API redeploy. For a GitHub-linked Heroku app, use the Heroku GitHub integration/manual deploy or provide the source tarball URL.");const r=await api().post("/apps/"+encodeURIComponent(app)+"/builds",{source_blob:{url:sourceUrl,version}});return {app,build_id:r.data.id,status:r.data.status,source_url:r.data.source_blob?.url};}
module.exports={listApps,info,formation,restart,stop,start,scale,releases,releaseInfo,rollback,builds,buildInfo,buildResult,cancelBuild,logs,configVars,setConfigVar,deleteConfigVar,maintenance,redeploy};