const path=require('path');
const commandHandler=require('./commandHandler');
const settings=require('../settings');
let initialized=false;const hooks={};
function loadModule(name){try{return require(path.join(__dirname,'..','plugins',name+'.js'));}catch(e){console.error('[PLUGIN] '+name+': '+e.message);return null;}}
function init(){if(initialized)return;commandHandler.loadCommands();for(const name of ['autoread','autotyping','antidelete','antilink','antitag','mention','chatbot','tictactoe'])hooks[name]=loadModule(name);initialized=true;console.log('TOHID-AI plugin runtime ready: '+commandHandler.commands.size+' commands');}
function isCommand(text){return(settings.prefixes||['.']).some(p=>String(text||'').startsWith(p));}
async function execute(sock,message,text,context={}){init();const prefixes=settings.prefixes||['.'];const plugin=commandHandler.getCommand(String(text||'').trim(),prefixes);if(!plugin||typeof plugin.handler!=='function')return false;const prefix=prefixes.find(p=>String(text||'').startsWith(p))||prefixes[0]||'.';const parts=String(text||'').slice(prefix.length).trim().split(/\\s+/).filter(Boolean);const args=parts.slice(1);if(plugin.ownerOnly&&!context.isOwner){await sock.sendMessage(message.key.remoteJid,{text:'Owner only.'},{quoted:message});return true;}if(plugin.groupOnly&&!context.isGroup){await sock.sendMessage(message.key.remoteJid,{text:'This command can only be used in groups.'},{quoted:message});return true;}await plugin.handler(sock,message,args,{...context,chatId:context.chatId||message.key.remoteJid,senderId:context.senderId||message.key.participant||message.key.remoteJid,prefix,command:parts[0]||plugin.command,settings});return true;}
async function onMessage(sock,message,text,context={}){init();const chatId=context.chatId||message.key.remoteJid,senderId=context.senderId||message.key.participant||chatId;const tasks=[];if(hooks.autoread?.handleAutoread)tasks.push(hooks.autoread.handleAutoread(sock,message));if(hooks.antidelete?.storeMessage)tasks.push(hooks.antidelete.storeMessage(sock,message));if(hooks.antitag?.handleTagDetection&&context.isGroup)tasks.push(hooks.antitag.handleTagDetection(sock,chatId,message,senderId));if(hooks.antilink?.handleIncomingMessage&&context.isGroup)tasks.push(hooks.antilink.handleIncomingMessage(sock,chatId,message,senderId));if(hooks.mention?.handleMentionDetection)tasks.push(hooks.mention.handleMentionDetection(sock,chatId,message));if(hooks.autotyping?.handleAutotypingForMessage)tasks.push(hooks.autotyping.handleAutotypingForMessage(sock,chatId,message));if(hooks.tictactoe?.handleTicTacToeMove&&text)tasks.push(hooks.tictactoe.handleTicTacToeMove(sock,chatId,senderId,text));if(hooks.chatbot?.handleChatbotResponse&&text)tasks.push(hooks.chatbot.handleChatbotResponse(sock,chatId,message,text,senderId));await Promise.allSettled(tasks);}
async function onMessageUpdate(sock,update){init();if(hooks.antidelete?.handleMessageRevocation)await hooks.antidelete.handleMessageRevocation(sock,update);}
function diagnostics(){init();return commandHandler.getDiagnostics();}
function reload(){commandHandler.reloadCommands();initialized=true;}
module.exports={init,execute,onMessage,onMessageUpdate,diagnostics,reload,isCommand};
